name: Pipeline
on: 
  push:
    branches:
      - main
      - gh-actions
  pull_request:
    branches:
      - main
jobs: 
  run-automated-tests:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code / fetch code
        uses: actions/checkout@v4

      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name:  Install dependencies
        run:  npm install 
      
      - name: Install Playwright browsers
        run: npx playwright install
      
      - name: Pull docker image
        run: docker pull rasilva1986/my-vue-app:v1

      # Step 5: Start application
      
      - name: Start application
        run: docker run --name hotelapp -d -p 3000:3000 rasilva1986/my-vue-app:v1

      # Step 6: Wait for application to start
      
      - name: Wait for application to start
        run: npx wait-on http://localhost:3000/

      - name: Run tests
        env:
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        run: npm run run-tests
      
      - name: Wait for server to start
        run: sleep 5
      
      - name: Save test run artifacts
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results
          path: ./playwright-report
          if-no-files-found: warn
          include-hidden-files: false

      - name: Save test output logs
        uses: actions/upload-artifact@v4
        with:
          name: test-output
          path: test-output.log
