name: Pipeline
on: 
  push:
    branches:
      - main
      - gh-actions
  pull_request:
    branches:
      - main
jobs: 
  run-automated-tests:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code / fetch code
        uses: actions/checkout@v4

      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install node packages
        run:  npm install 

      - name: Start application
        run: |
          npm run server &
          sleep 10 # Adjust this as needed
      
      - name: Load .env file
        run: echo "BASE_URL=http://localhost:3000" > .env

      - name: Run tests
        env:
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        run: npm run run-tests

      - name: Save test run artifacts
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results
          path: ./playwright-report
          if-no-files-found: warn
          include-hidden-files: false

      - name: Save test output logs
        uses: actions/upload-artifact@v4
        with:
          name: test-output
          path: test-output.log
